//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportEncPswds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public bool Active { get; set; }
        public bool ActiveInRotation { get; set; }
        public Nullable<int> BillingCodeID { get; set; }
        public int ContactID { get; set; }
        public Nullable<System.DateTime> DateInactive { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string MembershipUserName { get; set; }
        public int MortgageBrokerID { get; set; }
        public string MothersMaidenName { get; set; }
        public Nullable<System.DateTime> PointPurchased { get; set; }
        public string PDSUserFolderName { get; set; }
        public Nullable<System.DateTime> RetentionDate { get; set; }
        public Nullable<int> RecruiterUserID { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public int TextMessagingOptionID { get; set; }
        public Nullable<int> EmailMessagingOptionID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> PDSVersionID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> PointSubscribeDate { get; set; }
        public string UserNotes { get; set; }
        public string MyNotes { get; set; }
        public string PLAccountNumber { get; set; }
        public Nullable<System.DateTime> AnnualAdminFeeDate { get; set; }
        public Nullable<bool> HasDOAccount { get; set; }
        public Nullable<bool> HasLPAccount { get; set; }
        public Nullable<bool> HasCREDCOAccount { get; set; }
        public string DOUsername { get; set; }
        public string DOPassword { get; set; }
        public Nullable<decimal> OverrideFeeSelfProcessAdmin { get; set; }
        public string NMLS { get; set; }
        public Nullable<System.DateTime> NMLSNationalExamDate { get; set; }
        public Nullable<bool> NMLSRelationshipEstablished { get; set; }
        public Nullable<int> PrimaryMortgageBranchID { get; set; }
        public Nullable<int> FPFRepID { get; set; }
        public Nullable<int> CreditAgencyID { get; set; }
        public string CreditAgencyUsername { get; set; }
        public string CreditAgencyPassword { get; set; }
        public Nullable<int> CreditAgencyID2 { get; set; }
        public string CreditAgencyUsername2 { get; set; }
        public string CreditAgencyPassword2 { get; set; }
        public Nullable<bool> NMLSHasSponsorship { get; set; }
        public Nullable<bool> HasFPFDUAccount { get; set; }
        public Nullable<bool> NMLSRelationshipBranchEstablished { get; set; }
        public Nullable<bool> NMLSPE { get; set; }
        public Nullable<bool> AllowAppraisalOrdersForLP { get; set; }
        public bool EnableCRM { get; set; }
        public bool IsInCRM { get; set; }
        public Nullable<bool> EnableProcessorContactClient { get; set; }
        public Nullable<System.DateTime> EncompassMigrated { get; set; }
        public int FPFMailAcknowledgeCount { get; set; }
        public Nullable<bool> IsGroupAccount { get; set; }
        public string LegalFullName { get; set; }
        public Nullable<bool> IsSuspended { get; set; }
        public Nullable<int> ProfilePhotoFileId { get; set; }
        public string Bio { get; set; }
        public string ChangePasswordKey { get; set; }
        public Nullable<bool> IsOffLocation { get; set; }
        public Nullable<int> OutOfOfficeAssistUserID { get; set; }
        public Nullable<System.DateTime> OutOfOfficeExpired { get; set; }
        public Nullable<bool> OutOfOfficeCCMe { get; set; }
        public string EncLoginPswd { get; set; }
    }
}
